#!/bin/sh

set -xeu

git_dir=~/.local/share/dotfiles/git
GIT_DIR=$(git rev-parse --absolute-git-dir 2>/dev/null || echo $git_dir)
export GIT_DIR

if ! git config --local core.worktree >/dev/null; then
	if [ "${GIT_DIR:-}" != $git_dir ]; then
		mkdir -p "$(dirname $git_dir)"
		mv "$GIT_DIR" $git_dir
		GIT_DIR=$git_dir
	fi

	git config core.worktree ~
	git config include.path ~/.config/dotfiles/.gitconfig

	if [ -t 2 ]; then
		git diff --diff-filter=D --name-only -z | git -C ~ checkout --pathspec-from-file=- --pathspec-file-nul
	else
		: "Clobbering all dotfiles"
		git checkout @ ~
	fi
fi
unset GIT_DIR

ln -fs ~/.config/git/hooks/* ~/.config/git/template/hooks

chflags -v hidden pkg src setup tmp 2>/dev/null ||:

if type brew >/dev/null 2>&1; then
	HOMEBREW_NO_ENV_HINTS=1 brew bundle --file ~/.config/dotfiles/Brewfile
elif [ "$(uname -s)" = Darwin ]; then
	open https://brew.sh
	exit 1
fi

if ! command -v ruby >/dev/null; then
	exit 1
fi

if command -v apt-get >/dev/null; then
	sudo apt-get update --option DPkg::Lock::Timeout=60
	ruby -r ~/.local/share/dotfiles/package -e 'puts Package.APT' |
		xargs sudo apt-get install --option DPkg::Lock::Timeout=60 --yes
fi

if [ "$(uname -s)" = Darwin ] && ! test -f /etc/pam.d/sudo_local; then
	sudo sh -c "echo 'auth       sufficient     pam_tid.so' >/etc/pam.d/sudo_local"
	sudo -k
	tccutil reset All com.apple.Terminal
fi
