#!/bin/sh

set -xeu

GIT_DIR=$(git rev-parse --absolute-git-dir 2>/dev/null || echo ~/.dotfiles.git)
export GIT_DIR

if ! git config --local core.worktree >/dev/null; then
	[ "${GIT_DIR:-}" != ~/.dotfiles.git ] && mv "$GIT_DIR" ~/.dotfiles.git
	git --git-dir ~/.dotfiles.git config include.path .gitconfig
	if [ -t 2 ]; then
		git --git-dir ~/.dotfiles.git/ --work-tree ~ diff --diff-filter=D --name-only -z |
			git -C ~ --git-dir ~/.dotfiles.git/ checkout --pathspec-from-file=- --pathspec-file-nul
	else
		: "Clobbering all dotfiles"
		git --git-dir ~/.dotfiles.git --work-tree ~ checkout @ ~
	fi
	PATH=~/bin:$PATH

	dotfiles config core.worktree ~
fi

ln -fs ~/.config/git/hooks/* ~/.config/git/template/hooks

chflags -v hidden bin pkg src setup tmp 2>/dev/null ||:

if type brew >/dev/null 2>&1; then
	brew bundle --no-lock --file ~/.config/dotfiles/Brewfile
elif [ "$(uname -s)" = Darwin ]; then
	open https://brew.sh
	exit 1
elif command -v apt-get >/dev/null && command -v ruby >/dev/null; then
	sudo apt-get update --option DPkg::Lock::Timeout=60
	ruby -ryaml <<-EOF |
		puts YAML
		  .load_file("#{ENV.fetch("HOME")}/.config/dotfiles/packages.yaml").fetch("packages")
		  .filter_map { k, v = *Array(_1).first; v ? v.fetch("APT", k) : k }
		EOF
		xargs sudo apt-get install --option DPkg::Lock::Timeout=60 --yes
fi

if [ "$(uname -s)" = Darwin ] && ! test -f /etc/pam.d/sudo_local; then
	sudo sh -c "echo 'auth       sufficient     pam_tid.so' >/etc/pam.d/sudo_local"
	sudo -k
	tccutil reset All com.apple.Terminal
fi
