#!/bin/sh

set -xeu

GIT_DIR=$(git rev-parse --absolute-git-dir 2>/dev/null || echo ~/.dotfiles.git)
export GIT_DIR

if ! git config --local core.worktree >/dev/null; then
	[ "${GIT_DIR:-}" != ~/.dotfiles.git ] && mv "$GIT_DIR" ~/.dotfiles.git
	git --git-dir ~/.dotfiles.git --work-tree ~ checkout @ ~
	PATH=~/bin:$PATH

	dotfiles config core.worktree ~
	dotfiles config status.showUntrackedFiles no
	dotfiles config status.relativePaths false
	dotfiles config alias.edit '!$'"{EDITOR%% *} +0G"
	dotfiles config alias.update '!git pull && ./setup'
fi

ln -fs ~/.config/git/hooks/* ~/.config/git/template/hooks

chflags -v hidden bin src setup 2>/dev/null ||:

if type brew >/dev/null 2>&1; then
	brew bundle --global --no-lock
else
	if [ "$(uname -s)" = Darwin ]; then
		open https://brew.sh
		exit 1
	fi
	if [ ! -r /usr/share/bash-completion/bash_completion ]; then
		sudo apt-get install bash-completion --option DPkg::Lock::Timeout=60
	fi
fi

if [ "$(uname -s)" = Darwin ] && ! grep --quiet -F pam_tid.so /etc/pam.d/sudo; then
	sudo sed -i '' -e '1 { a\
		auth       sufficient     pam_tid.so
	}' /etc/pam.d/sudo
fi
