# vim: set ft=ruby
tap "homebrew/bundle"
tap "homebrew/services"

require "yaml"
YAML.load_file("#{__dir__}/packages.yaml")
  .fetch("packages")
  .filter_map { k, v = *Array(it).first; v ? v.fetch("Homebrew", k) : k }
  .each { brew it }

cask "dash"
cask "font-sf-mono"
cask "ghostty"
cask "keycastr"
cask "maccy"
cask "macvim-app"
