# vim: set ft=ruby
tap "homebrew/bundle"
tap "homebrew/services"

require "#{ENV["HOME"]}/.local/share/dotfiles/package"
Package.Homebrew.each { brew it }

cask "dash"
cask "font-sf-mono"
cask "ghostty"
cask "keycastr"
cask "maccy"
cask "macvim-app"
